### ISSUE TITLE
Implement Singleplayer Scene without VPS or Networking

### ISSUE THREAD

**Issue by ianfromdover** [ianfromdover/utown-green-ar#36]
for live demo

AR functionality (just like assignments that the students are doing)

we can show that this is something that we have learnt, this is possible. We can prove to stakeholders that we are making progress.

light up each other -> people gathering at the same fireplace point, let player interact with the virtual object
> sell the idea of gathering around a virtual object, instead of the interaction through virtual objects

**Comment by emranpoh** [comment]
- iOS

**Comment by ianfromdover** [comment]
using a phone: it is personal to you, your phone is more connected
iPad like holding up a tray like that, 'no feeling'

**Comment by emranpoh** [comment]
- [ ] @emranpoh to estimate requirements and deliverables for this issue
- [ ] @emranpoh update @ianfromdover on estimate to update karen.

**Comment by ianfromdover** [comment]
absolute worst case scenario: the fireplace will be wherever you just start the app
